init guardian form
cpe-kmutt-student/comcamp35 pull request #25
Opened 2024-02-15 04:03 UTC by NinePTH

2024-02-15 10:37 UTC, Mirailisc requested changes

2024-02-15 10:37 UTC, Mirailisc commented on src/components/EducationForm/index.tsx
> +          />
ใช้ Select แทน

2024-02-15 10:37 UTC, Mirailisc commented on src/components/EducationForm/index.tsx
> +          />
อันนี้คิดว่าใช้ Select ก็ดีนะ แต่ต้องลองดูอีกที

2024-02-15 10:37 UTC, Mirailisc commented on src/components/EducationForm/index.tsx
> +      gpax: data.gpax ?? '',
อันนี้ต้องเป็น 0 ป่ะ ถ้ามันป็น type number

2024-02-15 10:43 UTC, Mirailisc requested changes

2024-02-15 10:43 UTC, Mirailisc commented on src/components/EducationForm/index.module.scss
> +    }
ไอ้นี่ทำไร

2024-02-15 10:43 UTC, Mirailisc commented on src/components/EducationForm/index.module.scss
> +      }
ไอนี่ด้วย

2024-02-15 10:43 UTC, Mirailisc commented on src/components/EducationForm/index.tsx
> +  if (!values.gpax) errors.gpax = 'กรุณาระบุเกรดเฉลี่ยสะสม'
Nahhh

```ts
if (values.gpax === 0) ...
```

2024-02-19 04:54 UTC, NinePTH commented
Ok

2024-02-19 04:54 UTC, NinePTH commented
ละเขียนชื่อ commit ผิดด้วยไง

2024-02-25 15:28 UTC, NinePTH commented on src/components/EducationForm/index.module.scss
> +    }
เอา css อันเก่ามาละไม่ได้ลบ

2024-02-25 15:29 UTC, NinePTH commented on src/components/EducationForm/index.module.scss
> +      }
เอาไอ้ลูกศรชี้ขึ้นลงออกเวลาใช้ input num อะ หรือต้องเอาไว้

2024-02-25 15:31 UTC, NinePTH commented on src/components/EducationForm/index.tsx
> +          />
กูว่ามันมีหลายสายเกิน เลยกะว่าจะค้างเป็น textfield ไว้

2024-02-26 06:17 UTC, Mirailisc commented on src/components/EducationForm/index.tsx
> +          />
ไม่ดีเท่าไหร่เพราะมันต้องให้ data เป็นไปตามประเภทเดียวกัน

2024-02-26 06:17 UTC, Mirailisc commented on src/components/EducationForm/index.module.scss
> +      }
เอาไว้ๆ

2024-02-26 12:50 UTC, NinePTH commented on src/components/EducationForm/index.module.scss
> +      }
ok

2024-02-26 12:53 UTC, NinePTH commented on src/components/EducationForm/index.tsx
> +          />
งั้นต้องมี list สายที่เกี่ยวข้องอะ เพราะกูไม่รู้ว่าทั้งหมดที่รับมันมีอะไรบ้าง
![image](https://github.com/cpe-kmutt-student/comcamp35/assets/105841902/6bd17709-f88b-4abe-a554-c4fa57b4b5ea)

2024-02-27 18:20 UTC, merged